version: 2
updates:
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: monthly
    commit-message:
      prefix: 'build'
      include: scope

  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: monthly
    commit-message:
      prefix: 'build'
      include: scope
    groups:
      dev-patches:
        applies-to: version-updates
        dependency-type: development
        update-types:
          - patch

  - package-ecosystem: pip
    directory: '/'
    schedule:
      interval: monthly
    commit-message:
      prefix: 'build'
      include: scope
    groups:
      mkdocs:
        applies-to: version-updates
        patterns:
          - 'mkdocs*'
        update-types:
          - patch
          - minor
      development:
        applies-to: version-updates
        dependency-type: development
        update-types:
          - patch
          - minor
      production:
        applies-to: version-updates
        dependency-type: production
        update-types:
          - patch
          - minor
