name: Merge Queue

on:
  merge_group:

jobs:
  poetry-with-codecov:
    strategy:
      matrix:
        python-version: [ "3.10" ]
    uses: lars-reimann/.github/.github/workflows/poetry-codecov-reusable.yml@main
    with:
      working-directory: .
      python-version: ${{ matrix.python-version }}
      module-name: safeds
      coverage: false
