name: Publish Stdlib to PyPI

on:
  workflow_dispatch

jobs:
  poetry-with-codecov:
    strategy:
      matrix:
        python-version: [ "3.10" ]
    uses: lars-reimann/.github/.github/workflows/poetry-pypi-reusable.yml@main
    with:
      working-directory: src
      python-version: ${{ matrix.python-version }}
    secrets:
      PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
