name: Release to PyPI

on:
  workflow_dispatch

jobs:
  release:
    uses: lars-reimann/.github/.github/workflows/poetry-pypi-reusable.yml@main
    with:
      working-directory: src
      python-version: "3.10"
    secrets:
      PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
    permissions:
      contents: write
