name: Release to PyPI

on:
  workflow_dispatch

jobs:
  release:
    uses: lars-reimann/.github/.github/workflows/poetry-pypi-reusable.yml@main
    with:
      working-directory: .
      python-version: "3.11"
    secrets:
      GITHUB_PAT: ${{ secrets.PAT }}
      PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
